DROP TABLE IF EXISTS govschool CASCADE;
CREATE TABLE govschool (
	id int(11) NOT NULL,
	villagemapsurveyid int(11),
	whichclass int(2),
	whichclassother varchar(15),
	typeofschool int(1),
	mediumofschool int(1),
	mediumofschoolother varchar(15),
	emiscode int(20),
	establishedyear int(4),
	isngoaffiliated tinyint unsigned,
	ngoname varchar(50),
	ngoworkstartedyear int(4),
	projecttype int(1),
	teacherseducationmatric int(3),
	teacherseducationinter int(3),
	teacherseducationgraduate int(3),
	teacherseducationmaster int(3),
	teacherseducationpostgraduate int(3),
	teacherseducationother int(3),
	teachersprofessionalct int(3),
	teachersprofessionalptc int(3),
	teachersprofessionalbed int(3),
	teachersprofessionalmed int(3),
	teachersprofessionalother int(3),
	teachersgottrainingnone int(3),
	teachersgottrainingof15days int(3),
	teachersgottrainingof3days int(3),
	teachersgottrainingof3more int(3),
	totalrooms int(3),
	totalclassrooms int(3),
	isdrinkingwateravailable tinyint unsigned,
	isboundarywallavailable tinyint unsigned,
	istoiletavailable tinyint unsigned,
	islibraryhasbooks tinyint unsigned,
	islibrarybooksavailable tinyint unsigned,
	isplaygroundavailable tinyint unsigned,
	issportsteacheravailable tinyint unsigned,
	islaboratoryavailable tinyint unsigned,
	iscomputelabavailable tinyint unsigned,
	isinternetavailable tinyint unsigned,
	whoprovidedfundsinformation int(3),
	isfundactive tinyint unsigned,
	totalmembers int(5),
	activemembers int(5),
	bankbalance int(10),
	isclass2childrenmixed tinyint unsigned ,
	class2childrenmixedwith varchar(50),
	isclass8childrenmixed tinyint unsigned,
	class8childrenmixedwith varchar(50),
	class2childrenseatedwhere int(2),
	class8childrenseatedwhere int(2),
	isclass2haveblackboard tinyint unsigned,
	isclass8haveblackboard tinyint unsigned,
	isclass2havebooks tinyint unsigned,
	isclass8havebooks tinyint unsigned,
	isclass2havesupplimentarymaterial tinyint unsigned,
	isclass8havesupplimentarymaterial tinyint unsigned,
	totalenrollment int(5),
	totalattendance int(5),
	classkachi int(5),
	classpakki int(5),
	class1 int(5),
	class2 int(5),
	class3 int(5),
	class4 int(5),
	class5 int(5),
	class6 int(5),
	class7 int(5),
	class8 int(5),
	class9 int(5),
	class10 int(5),
	totalappointed int(5),
	totalpresent int(5),
	recordyear int(4),
	isfundspentonnewclassrooms tinyint unsigned,
	isfundspentonnewverandah tinyint unsigned,
	isfundspentonnewtoilets tinyint unsigned,
	isfundspentonnewmaingate tinyint unsigned,
	isfundspentonboundarywall tinyint unsigned,
	isfundspentonnewfurniture tinyint unsigned,
	isfundspentonnewlearningmaterial tinyint unsigned,
	isfundspentonnewstationery tinyint unsigned,
	isfundspentonnewlibrarybooks tinyint unsigned,
	isfundspentonwhitewash tinyint unsigned,
	isfundspentonrepairclassrooms tinyint unsigned,
	isfundspentonrepairbuilding tinyint unsigned,
	isfundspentonrepairtoilets tinyint unsigned,
	isfundspentonrepairfurniture tinyint unsigned,
	isfundspentonrepairwaterfacility tinyint unsigned,
	isfundspentonrepaircomputers tinyint unsigned,
	isfundspentonparateachersalary tinyint unsigned,
	isfundspentonuniforms tinyint unsigned,
	PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
LOAD DATA INFILE 'govschool.csv' INTO table govschool
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
(
	id,
	villagemapsurveyid,
	whichclass,
	whichclassother,
	typeofschool,
	@mediumofschool,
	mediumofschoolother,
	@emiscode,
	@establishedyear,
	@isngoaffiliated,
	ngoname,
	@ngoworkstartedyear,
	@projecttype,
	@teacherseducationmatric,
	@teacherseducationinter,
	@teacherseducationgraduate,
	@teacherseducationmaster,
	@teacherseducationpostgraduate,
	@teacherseducationother,
	@teachersprofessionalct,
	@teachersprofessionalptc,
	@teachersprofessionalbed,
	@teachersprofessionalmed,
	@teachersprofessionalother,
	@teachersgottrainingnone,
	@teachersgottrainingof15days,
	@teachersgottrainingof3days,
	@teachersgottrainingof3more,
	@totalrooms,
	@totalclassrooms,
	@isdrinkingwateravailable,
	@isboundarywallavailable,
	@istoiletavailable,
	@islibraryhasbooks,
	@islibrarybooksavailable,
	@isplaygroundavailable,
	@issportsteacheravailable,
	@islaboratoryavailable,
	@iscomputelabavailable,
	@isinternetavailable,
	@whoprovidedfundsinformation,
	@isfundactive,
	@totalmembers,
	@activemembers,
	@bankbalance,
	@isclass2childrenmixed,
	class2childrenmixedwith,
	@isclass8childrenmixed,
	class8childrenmixedwith,
	@class2childrenseatedwhere,
	@class8childrenseatedwhere,
	@isclass2haveblackboard,
	@isclass8haveblackboard,
	@isclass2havebooks,
	@isclass8havebooks,
	@isclass2havesupplimentarymaterial,
	@isclass8havesupplimentarymaterial,
	@totalenrollment,
	@totalattendance,
	@classkachi,
	@classpakki,
	@class1,
	@class2,
	@class3,
	@class4,
	@class5,
	@class6,
	@class7,
	@class8,
	@class9,
	@class10,
	@totalappointed,
	@totalpresent,
	@recordyear,
	@isfundspentonnewclassrooms,
	@isfundspentonnewverandah,
	@isfundspentonnewtoilets,
	@isfundspentonnewmaingate,
	@isfundspentonboundarywall,
	@isfundspentonnewfurniture,
	@isfundspentonnewlearningmaterial,
	@isfundspentonnewstationery,
	@isfundspentonnewlibrarybooks,
	@isfundspentonwhitewash,
	@isfundspentonrepairclassrooms,
	@isfundspentonrepairbuilding,
	@isfundspentonrepairtoilets,
	@isfundspentonrepairfurniture,
	@isfundspentonrepairwaterfacility,
	@isfundspentonrepaircomputers,
	@isfundspentonparateachersalary,
	@isfundspentonuniforms
)
SET mediumofschool = NULLIF(@mediumofschool, ''),
	establishedyear = NULLIF(@establishedyear, ''),
	isngoaffiliated = ( CASE WHEN @isngoaffiliated = -1 THEN 1 WHEN @isngoaffiliated = 0 THEN 0 WHEN @isngoaffiliated = '' THEN NULL END),
	ngoworkstartedyear = NULLIF(@ngoworkstartedyear, ''),
	isclass2haveblackboard= ( CASE WHEN @isclass2haveblackboard = -1 THEN 1 WHEN @isclass2haveblackboard = 0 THEN 0 WHEN @isclass2haveblackboard = '' THEN NULL END),
	isclass8haveblackboard= ( CASE WHEN @isclass8haveblackboard = -1 THEN 1 WHEN @isclass8haveblackboard = 0 THEN 0 WHEN @isclass8haveblackboard = '' THEN NULL END),
	isclass2havebooks= ( CASE WHEN @isclass2havebooks = -1 THEN 1 WHEN @isclass2havebooks = 0 THEN 0 WHEN @isclass2havebooks = '' THEN NULL END),
	isclass8havebooks= ( CASE WHEN @isclass8havebooks = -1 THEN 1 WHEN @isclass8havebooks = 0 THEN 0 WHEN @isclass8havebooks = '' THEN NULL END),
	isclass2havesupplimentarymaterial= ( CASE WHEN @isclass2havesupplimentarymaterial = -1 THEN 1 WHEN @isclass2havesupplimentarymaterial = 0 THEN 0 WHEN @isclass2havesupplimentarymaterial = '' THEN NULL END),
	isclass8havesupplimentarymaterial= ( CASE WHEN @isclass8havesupplimentarymaterial = -1 THEN 1 WHEN @isclass8havesupplimentarymaterial = 0 THEN 0 WHEN @isclass8havesupplimentarymaterial = '' THEN NULL END),
	teacherseducationmatric = NULLIF(@teacherseducationmatric,''),
	teacherseducationinter = NULLIF(@teacherseducationinter,''),
	teacherseducationgraduate = NULLIF(@teacherseducationgraduate,''),
	teacherseducationmaster = NULLIF(@teacherseducationmaster,''),
	teacherseducationpostgraduate = NULLIF(@teacherseducationpostgraduate,''),
	teacherseducationother = NULLIF(@teacherseducationother,''),
	teachersprofessionalct = NULLIF(@teachersprofessionalct,''),
	teachersprofessionalptc = NULLIF(@teachersprofessionalptc,''),
	teachersprofessionalbed = NULLIF(@teachersprofessionalbed,''),
	teachersprofessionalmed = NULLIF(@teachersprofessionalmed,''),
	teachersprofessionalother = NULLIF(@teachersprofessionalother,''),
	teachersgottrainingnone = NULLIF(@teachersgottrainingnone,''),
	teachersgottrainingof15days = NULLIF(@teachersgottrainingof15days,''),
	teachersgottrainingof3days = NULLIF(@teachersgottrainingof3days,''),
	teachersgottrainingof3more = NULLIF(@teachersgottrainingof3more,''),
	totalrooms = NULLIF(@totalrooms,''),
	totalclassrooms = NULLIF(@totalclassrooms,''),
	totalenrollment = NULLIF(@totalenrollment,''),
	totalattendance = NULLIF(@totalattendance,''),
	classkachi = NULLIF(@classkachi,''),
	classpakki = NULLIF(@classpakki,''),
	class1 = NULLIF(@class1,''),
	class2 = NULLIF(@class2,''),
	class3 = NULLIF(@class3,''),
	class4 = NULLIF(@class4,''),
	class5 = NULLIF(@class5,''),
	class6 = NULLIF(@class6,''),
	class7 = NULLIF(@class7,''),
	class8 = NULLIF(@class8,''),
	class9 = NULLIF(@class9,''),
	class10 = NULLIF(@class10,''),
	totalappointed = NULLIF(@totalappointed,''),
	totalpresent = NULLIF(@totalpresent,''),
	class2childrenseatedwhere = NULLIF(@class2childrenseatedwhere,''),
	class8childrenseatedwhere = NULLIF(@class8childrenseatedwhere,''),
	whoprovidedfundsinformation = NULLIF(@whoprovidedfundsinformation, ''),
	isfundactive = ( CASE WHEN @isfundactive = -1 THEN 1 WHEN @isfundactive = 0 THEN 0 WHEN @isfundactive = '' THEN NULL END),
	totalmembers = NULLIF(@totalmembers,''),
	activemembers = NULLIF(@activemembers,''),
	isdrinkingwateravailable = ( CASE WHEN @isdrinkingwateravailable = -1 THEN 1 WHEN @isdrinkingwateravailable = 0 THEN 0 WHEN @isdrinkingwateravailable = '' THEN NULL END),
	isboundarywallavailable = ( CASE WHEN @isboundarywallavailable = -1 THEN 1 WHEN @isboundarywallavailable = 0 THEN 0 WHEN @isboundarywallavailable = '' THEN NULL END),
	istoiletavailable = ( CASE WHEN @istoiletavailable = -1 THEN 1 WHEN @istoiletavailable = 0 THEN 0 WHEN @istoiletavailable = '' THEN NULL END),
	islibraryhasbooks = ( CASE WHEN @islibraryhasbooks = -1 THEN 1 WHEN @islibraryhasbooks = 0 THEN 0 WHEN @islibraryhasbooks = '' THEN NULL END),
	islibrarybooksavailable = ( CASE WHEN @islibrarybooksavailable = -1 THEN 1 WHEN @islibrarybooksavailable = 0 THEN 0 WHEN @islibrarybooksavailable = '' THEN NULL END),
	isplaygroundavailable = ( CASE WHEN @isplaygroundavailable = -1 THEN 1 WHEN @isplaygroundavailable = 0 THEN 0 WHEN @isplaygroundavailable = '' THEN NULL END),
	issportsteacheravailable = ( CASE WHEN @issportsteacheravailable = -1 THEN 1 WHEN @issportsteacheravailable = 0 THEN 0 WHEN @issportsteacheravailable = '' THEN NULL END),
	islaboratoryavailable = ( CASE WHEN @islaboratoryavailable = -1 THEN 1 WHEN @islaboratoryavailable = 0 THEN 0 WHEN @islaboratoryavailable = '' THEN NULL END),
	iscomputelabavailable = ( CASE WHEN @iscomputelabavailable = -1 THEN 1 WHEN @iscomputelabavailable = 0 THEN 0 WHEN @iscomputelabavailable = '' THEN NULL END),
	isinternetavailable = ( CASE WHEN @isinternetavailable = -1 THEN 1 WHEN @isinternetavailable = 0 THEN 0 WHEN @isinternetavailable = '' THEN NULL END),
	isclass2childrenmixed = ( CASE WHEN @isclass2childrenmixed = 1 THEN 1 WHEN @isclass2childrenmixed = 0 THEN 0 WHEN @isclass2childrenmixed = '' THEN NULL END),
	isclass8childrenmixed = ( CASE WHEN @isclass8childrenmixed = 1 THEN 1 WHEN @isclass8childrenmixed = 0 THEN 0 WHEN @isclass8childrenmixed = '' THEN NULL END),
	recordyear = NULLIF(@recordyear,''),
	isfundspentonnewclassrooms = ( CASE WHEN @isfundspentonnewclassrooms = 1 THEN 1 WHEN @isfundspentonnewclassrooms = 0 THEN 0 WHEN @isfundspentonnewclassrooms = '' THEN NULL END),
	isfundspentonnewverandah = ( CASE WHEN @isfundspentonnewverandah = 1 THEN 1 WHEN @isfundspentonnewverandah = 0 THEN 0 WHEN @isfundspentonnewverandah = '' THEN NULL END),
	isfundspentonnewtoilets = ( CASE WHEN @isfundspentonnewtoilets = 1 THEN 1 WHEN @isfundspentonnewtoilets = 0 THEN 0 WHEN @isfundspentonnewtoilets = '' THEN NULL END),
	isfundspentonnewmaingate = ( CASE WHEN @isfundspentonnewmaingate = 1 THEN 1 WHEN @isfundspentonnewmaingate = 0 THEN 0 WHEN @isfundspentonnewmaingate = '' THEN NULL END),
	isfundspentonboundarywall = ( CASE WHEN @isfundspentonboundarywall = 1 THEN 1 WHEN @isfundspentonboundarywall = 0 THEN 0 WHEN @isfundspentonboundarywall = '' THEN NULL END),
	isfundspentonnewfurniture = ( CASE WHEN @isfundspentonnewfurniture = 1 THEN 1 WHEN @isfundspentonnewfurniture = 0 THEN 0 WHEN @isfundspentonnewfurniture = '' THEN NULL END),
	isfundspentonnewlearningmaterial = ( CASE WHEN @isfundspentonnewlearningmaterial = 1 THEN 1 WHEN @isfundspentonnewlearningmaterial = 0 THEN 0 WHEN @isfundspentonnewlearningmaterial = '' THEN NULL END),
	isfundspentonnewstationery = ( CASE WHEN @isfundspentonnewstationery = 1 THEN 1 WHEN @isfundspentonnewstationery = 0 THEN 0 WHEN @isfundspentonnewstationery = '' THEN NULL END),
	isfundspentonnewlibrarybooks = ( CASE WHEN @isfundspentonnewlibrarybooks = 1 THEN 1 WHEN @isfundspentonnewlibrarybooks = 0 THEN 0 WHEN @isfundspentonnewlibrarybooks = '' THEN NULL END),
	isfundspentonwhitewash = ( CASE WHEN @isfundspentonwhitewash = 1 THEN 1 WHEN @isfundspentonwhitewash = 0 THEN 0 WHEN @isfundspentonwhitewash = '' THEN NULL END),
	isfundspentonrepairclassrooms = ( CASE WHEN @isfundspentonrepairclassrooms = 1 THEN 1 WHEN @isfundspentonrepairclassrooms = 0 THEN 0 WHEN @isfundspentonrepairclassrooms = '' THEN NULL END),
	isfundspentonrepairbuilding = ( CASE WHEN @isfundspentonrepairbuilding = 1 THEN 1 WHEN @isfundspentonrepairbuilding = 0 THEN 0 WHEN @isfundspentonrepairbuilding = '' THEN NULL END),
	isfundspentonrepairtoilets = ( CASE WHEN @isfundspentonrepairtoilets = 1 THEN 1 WHEN @isfundspentonrepairtoilets = 0 THEN 0 WHEN @isfundspentonrepairtoilets = '' THEN NULL END),
	isfundspentonrepairfurniture = ( CASE WHEN @isfundspentonrepairfurniture = 1 THEN 1 WHEN @isfundspentonrepairfurniture = 0 THEN 0 WHEN @isfundspentonrepairfurniture = '' THEN NULL END),
	isfundspentonrepairwaterfacility = ( CASE WHEN @isfundspentonrepairwaterfacility = 1 THEN 1 WHEN @isfundspentonrepairwaterfacility = 0 THEN 0 WHEN @isfundspentonrepairwaterfacility = '' THEN NULL END),
	isfundspentonrepaircomputers = ( CASE WHEN @isfundspentonrepaircomputers = 1 THEN 1 WHEN @isfundspentonrepaircomputers = 0 THEN 0 WHEN @isfundspentonrepaircomputers = '' THEN NULL END),
	isfundspentonparateachersalary = ( CASE WHEN @isfundspentonparateachersalary = 1 THEN 1 WHEN @isfundspentonparateachersalary = 0 THEN 0 WHEN @isfundspentonparateachersalary = '' THEN NULL END),
	isfundspentonuniforms = ( CASE WHEN @isfundspentonuniforms = 1 THEN 1 WHEN @isfundspentonuniforms = 0 THEN 0 WHEN @isfundspentonuniforms = '' THEN NULL END),
	projecttype = NULLIF(@projecttype, ''),
	emiscode = NULLIF(@emiscode, ''),
	bankbalance = NULLIF(@bankbalance, '');
commit;
select * from govschool;