DROP TABLE IF EXISTS householdchild CASCADE;
CREATE TABLE householdchild (
	`id` int(11) NOT NULL,
	`hhid` int(11) NOT NULL,
	`childage` int(3),
	`childgender` varchar(2),
	`childeducationne` tinyint UNSIGNED ,
	`childeducationdp` tinyint UNSIGNED ,
	`childeducationen` tinyint UNSIGNED ,
	`childdropoutclass` varchar(10),
	`childschoolclass` varchar(10),
	`childschoolgov` tinyint UNSIGNED ,
	`childschoolprivate` tinyint UNSIGNED ,
	`childschoolmadrs` tinyint UNSIGNED ,
	`childschoolnfe` tinyint UNSIGNED ,
	`childschoolother` int(2),
	`tuitionyes` tinyint UNSIGNED ,
	`tuitionno` tinyint UNSIGNED ,
	`readingbeginner` tinyint UNSIGNED ,
	`readingletter` tinyint UNSIGNED ,
	`readingword` tinyint UNSIGNED ,
	`readingsentance` tinyint UNSIGNED ,
	`readingstory` tinyint UNSIGNED ,
	`mathbeginner` tinyint UNSIGNED ,
	`math1_9` tinyint UNSIGNED ,
	`math11_99` tinyint UNSIGNED ,
	`mathsubstration` tinyint UNSIGNED ,
	`mathdivision` tinyint UNSIGNED ,
	`englishbeginner` tinyint UNSIGNED ,
	`englishcletter` tinyint UNSIGNED ,
	`englishsletter` tinyint UNSIGNED ,
	`englishword` tinyint UNSIGNED ,
	`englishsentance` tinyint UNSIGNED ,
	`childnotavailable` tinyint UNSIGNED ,
	PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
LOAD DATA INFILE 'householdchild.csv' INTO table householdchild
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
(
	id,
	hhid,
	@childage,
	childgender,
	@childeducationne,
	@childeducationdp,
	@childeducationen,
	@childdropoutclass,
	@childschoolclass,
	@childschoolgov,
	@childschoolprivate,
	@childschoolmadrs,
	@childschoolnfe,
	@childschoolother,
	@tuitionyes,
	@tuitionno,
	@readingbeginner,
	@readingletter,
	@readingword,
	@readingsentance,
	@readingstory,
	@mathbeginner,
	@math1_9,
	@math11_99,
	@mathsubstration,
	@mathdivision,
	@englishbeginner,
	@englishcletter,
	@englishsletter,
	@englishword,
	@englishsentance,
	@childnotavailable
)
SET childage = NULLIF(@childage, ''),
	childeducationne = ( CASE WHEN @childeducationne = '' THEN 0 WHEN @childeducationne = 1 THEN 1 END),
	childeducationdp = ( CASE WHEN @childeducationdp = '' THEN 0 WHEN @childeducationdp = 1 THEN 1 END),
	childeducationen = ( CASE WHEN @childeducationen = '' THEN 0 WHEN @childeducationen = 1 THEN 1 END),
	childdropoutclass = NULLIF(@childdropoutclass, ''),
	childschoolclass = NULLIF(@childschoolclass, ''),
	childschoolgov = ( CASE WHEN @childschoolgov = '' THEN 0 WHEN @childschoolgov = 1 THEN 1 END),
	childschoolprivate = ( CASE WHEN @childschoolprivate = '' THEN 0 WHEN @childschoolprivate = 1 THEN 1 END),
	childschoolmadrs = ( CASE WHEN @childschoolmadrs = '' THEN 0 WHEN @childschoolmadrs = 1 THEN 1 END),
	childschoolnfe = ( CASE WHEN @childschoolnfe = '' THEN 0 WHEN @childschoolnfe = 1 THEN 1 END),
	childschoolother = ( CASE WHEN @childschoolother = '' THEN 0 WHEN @childschoolother = 1 THEN 1 END),
	tuitionyes = ( CASE WHEN @tuitionyes = '' THEN 0 WHEN @tuitionyes = 1 THEN 1 END),
	tuitionno = ( CASE WHEN @tuitionno = '' THEN 0 WHEN @tuitionno = 1 THEN 1 END),
	readingbeginner = ( CASE WHEN @readingbeginner = '' THEN 0 WHEN @readingbeginner = 1 THEN 1 END),
	readingletter = ( CASE WHEN @readingletter = '' THEN 0 WHEN @readingletter = 1 THEN 1 END),
	readingword = ( CASE WHEN @readingword = '' THEN 0 WHEN @readingword = 1 THEN 1 END),
	readingsentance = ( CASE WHEN @readingsentance = '' THEN 0 WHEN @readingsentance = 1 THEN 1 END),
	readingstory = ( CASE WHEN @readingstory = '' THEN 0 WHEN @readingstory = 1 THEN 1 END),
	mathbeginner = ( CASE WHEN @mathbeginner = '' THEN 0 WHEN @mathbeginner = 1 THEN 1 END),
	math1_9 = ( CASE WHEN @math1_9 = '' THEN 0 WHEN @math1_9 = 1 THEN 1 END),
	math11_99 = ( CASE WHEN @math11_99 = '' THEN 0 WHEN @math11_99 = 1 THEN 1 END),
	mathsubstration = ( CASE WHEN @mathsubstration = '' THEN 0 WHEN @mathsubstration = 1 THEN 1 END),
	mathdivision = ( CASE WHEN @mathdivision = '' THEN 0 WHEN @mathdivision = 1 THEN 1 END),
	englishbeginner = ( CASE WHEN @englishbeginner = '' THEN 0 WHEN @englishbeginner = 1 THEN 1 END),
	englishcletter = ( CASE WHEN @englishcletter = '' THEN 0 WHEN @englishcletter = 1 THEN 1 END),
	englishsletter = ( CASE WHEN @englishsletter = '' THEN 0 WHEN @englishsletter = 1 THEN 1 END),
	englishword = ( CASE WHEN @englishword = '' THEN 0 WHEN @englishword = 1 THEN 1 END),
	englishsentance = ( CASE WHEN @englishsentance = '' THEN 0 WHEN @englishsentance = 1 THEN 1 END),
	childnotavailable = ( CASE WHEN @childnotavailable = 0 THEN 0 WHEN @childnotavailable = 1 THEN 1 END);
commit;
select * from householdchild;