DROP TABLE IF EXISTS privateschool CASCADE;
CREATE TABLE privateschool (
	id int(11) NOT NULL,
	villagemapsurveyid int(11),
	whichclass int(2),
	whichclassother varchar(15),
	typeofschool int(1),
	mediumofschool int(1),
	mediumofschoolother varchar(15),
	establishedyear int(4),
	isngoaffiliated tinyint unsigned,
	ngoname varchar(50),
	ngoworkstartedyear int(4),
 	comments varchar(500),
	teacherseducationmatric int(3),
	teacherseducationinter int(3),
	teacherseducationgraduate int(3),
	teacherseducationmaster int(3),
	teacherseducationpostgraduate int(3),
	teacherseducationother int(3),
	teachersprofessionalct int(3),
	teachersprofessionalptc int(3),
	teachersprofessionalbed int(3),
	teachersprofessionalmed int(3),
	teachersprofessionalother int(3),
	totalrooms int(3),
	totalclassrooms int(3),
	isdrinkingwateravailable tinyint unsigned,
	isboundarywallavailable tinyint unsigned,
	istoiletavailable tinyint unsigned,
	islibraryhasbooks tinyint unsigned,
	islibrarybooksavailable tinyint unsigned,
	isplaygroundavailable tinyint unsigned,
	issportsteacheravailable tinyint unsigned,
	islaboratoryavailable tinyint unsigned,
	iscomputelabavailable tinyint unsigned,
	isinternetavailable tinyint unsigned,
	whoprovidedfundsinformation int(3),
	isclass2childrenmixed tinyint unsigned ,
	class2childrenmixedwith varchar(50),
	isclass8childrenmixed tinyint unsigned,
	class8childrenmixedwith varchar(50),
	class2childrenseatedwhere int(2),
	class8childrenseatedwhere int(2),
	isclass2haveblackboard tinyint unsigned,
	isclass8haveblackboard tinyint unsigned,
	isclass2havebooks tinyint unsigned,
	isclass8havebooks tinyint unsigned,
	isclass2havesupplimentarymaterial tinyint unsigned,
	isclass8havesupplimentarymaterial tinyint unsigned,
	totalenrollment int(5),
	totalattendance int(5),
	recordtype int(2),
	classkg int(5),
	class1 int(5),
	class2 int(5),
	class3 int(5),
	class4 int(5),
	class5 int(5),
	class6 int(5),
	class7 int(5),
	class8 int(5),
	class9 int(5),
	class10 int(5),
	totalappointed int(5),
	totalpresent int(5),
	islastyeargotfunds tinyint unsigned,
	isthisyeargotfunds tinyint unsigned,
	lastyearfundamount int(10),
	thisyearfundamount int(10),
	lastyearfundreceivedmonth varchar(15),
	thisyearfundreceivedmonth varchar(15),
	lastyearfundreceivedfrom varchar(50),
	thisyearfundreceivedfrom varchar(50),
	PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
LOAD DATA INFILE 'privateschool.csv' INTO table privateschool
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
(
	id,
	villagemapsurveyid,
	whichclass,
	whichclassother,
	typeofschool,
	@mediumofschool,
	mediumofschoolother,
	@establishedyear,
	@isngoaffiliated,
	ngoname,
	@ngoworkstartedyear,
	comments,
	@teacherseducationmatric,
	@teacherseducationinter,
	@teacherseducationgraduate,
	@teacherseducationmaster,
	@teacherseducationpostgraduate,
	@teacherseducationother,
	@teachersprofessionalct,
	@teachersprofessionalptc,
	@teachersprofessionalbed,
	@teachersprofessionalmed,
	@teachersprofessionalother,
	@totalrooms,
	@totalclassrooms,
	@isdrinkingwateravailable,
	@isboundarywallavailable,
	@istoiletavailable,
	@islibraryhasbooks,
	@islibrarybooksavailable,
	@isplaygroundavailable,
	@issportsteacheravailable,
	@islaboratoryavailable,
	@iscomputelabavailable,
	@isinternetavailable,
	@whoprovidedfundsinformation,
	@isclass2childrenmixed,
	class2childrenmixedwith,
	@isclass8childrenmixed,
	class8childrenmixedwith,
	@class2childrenseatedwhere,
	@class8childrenseatedwhere,
	@isclass2haveblackboard,
	@isclass8haveblackboard,
	@isclass2havebooks,
	@isclass8havebooks,
	@isclass2havesupplimentarymaterial,
	@isclass8havesupplimentarymaterial,
	@totalenrollment,
	@totalattendance,
	recordtype,
	@classkg,
	@class1,
	@class2,
	@class3,
	@class4,
	@class5,
	@class6,
	@class7,
	@class8,
	@class9,
	@class10,
	@totalappointed,
	@totalpresent,
	@islastyeargotfunds,
	@isthisyeargotfunds,
	@lastyearfundamount,
	@thisyearfundamount,
	@lastyearfundreceivedmonth,
	@thisyearfundreceivedmonth,
	@lastyearfundreceivedfrom,
	@thisyearfundreceivedfrom
)
SET mediumofschool = NULLIF(@mediumofschool, ''),
	establishedyear = NULLIF(@establishedyear, ''),
	isngoaffiliated = ( CASE WHEN @isngoaffiliated = -1 THEN 1 WHEN @isngoaffiliated = 0 THEN 0 WHEN @isngoaffiliated = '' THEN NULL END),
	ngoworkstartedyear = NULLIF(@ngoworkstartedyear, ''),
	isclass2haveblackboard= ( CASE WHEN @isclass2haveblackboard = -1 THEN 1 WHEN @isclass2haveblackboard = 0 THEN 0 WHEN @isclass2haveblackboard = '' THEN NULL END),
	isclass8haveblackboard= ( CASE WHEN @isclass8haveblackboard = -1 THEN 1 WHEN @isclass8haveblackboard = 0 THEN 0 WHEN @isclass8haveblackboard = '' THEN NULL END),
	isclass2havebooks= ( CASE WHEN @isclass2havebooks = -1 THEN 1 WHEN @isclass2havebooks = 0 THEN 0 WHEN @isclass2havebooks = '' THEN NULL END),
	isclass8havebooks= ( CASE WHEN @isclass8havebooks = -1 THEN 1 WHEN @isclass8havebooks = 0 THEN 0 WHEN @isclass8havebooks = '' THEN NULL END),
	isclass2havesupplimentarymaterial= ( CASE WHEN @isclass2havesupplimentarymaterial = -1 THEN 1 WHEN @isclass2havesupplimentarymaterial = 0 THEN 0 WHEN @isclass2havesupplimentarymaterial = '' THEN NULL END),
	isclass8havesupplimentarymaterial= ( CASE WHEN @isclass8havesupplimentarymaterial = -1 THEN 1 WHEN @isclass8havesupplimentarymaterial = 0 THEN 0 WHEN @isclass8havesupplimentarymaterial = '' THEN NULL END),
	teacherseducationmatric = NULLIF(@teacherseducationmatric,''),
	teacherseducationinter = NULLIF(@teacherseducationinter,''),
	teacherseducationgraduate = NULLIF(@teacherseducationgraduate,''),
	teacherseducationmaster = NULLIF(@teacherseducationmaster,''),
	teacherseducationpostgraduate = NULLIF(@teacherseducationpostgraduate,''),
	teacherseducationother = NULLIF(@teacherseducationother,''),
	teachersprofessionalct = NULLIF(@teachersprofessionalct,''),
	teachersprofessionalptc = NULLIF(@teachersprofessionalptc,''),
	teachersprofessionalbed = NULLIF(@teachersprofessionalbed,''),
	teachersprofessionalmed = NULLIF(@teachersprofessionalmed,''),
	teachersprofessionalother = NULLIF(@teachersprofessionalother,''),
	totalrooms = NULLIF(@totalrooms,''),
	totalclassrooms = NULLIF(@totalclassrooms,''),
	totalenrollment = NULLIF(@totalenrollment,''),
	totalattendance = NULLIF(@totalattendance,''),
	classkg = NULLIF(@classkg,''),
	class1 = NULLIF(@class1,''),
	class2 = NULLIF(@class2,''),
	class3 = NULLIF(@class3,''),
	class4 = NULLIF(@class4,''),
	class5 = NULLIF(@class5,''),
	class6 = NULLIF(@class6,''),
	class7 = NULLIF(@class7,''),
	class8 = NULLIF(@class8,''),
	class9 = NULLIF(@class9,''),
	class10 = NULLIF(@class10,''),
	totalappointed = NULLIF(@totalappointed,''),
	totalpresent = NULLIF(@totalpresent,''),
	lastyearfundamount = NULLIF(@lastyearfundamount,''),
	thisyearfundamount = NULLIF(@thisyearfundamount,''),
	lastyearfundreceivedmonth = NULLIF(@lastyearfundreceivedmonth,''),
	thisyearfundreceivedmonth = NULLIF(@thisyearfundreceivedmonth,''),
	lastyearfundreceivedfrom = NULLIF(@lastyearfundreceivedfrom,''),
	thisyearfundreceivedfrom = NULLIF(@thisyearfundreceivedfrom,''),
	class2childrenseatedwhere = NULLIF(@class2childrenseatedwhere,''),
	class8childrenseatedwhere = NULLIF(@class8childrenseatedwhere,''),
	whoprovidedfundsinformation = NULLIF(@whoprovidedfundsinformation, ''),
	isdrinkingwateravailable = ( CASE WHEN @isdrinkingwateravailable = 1 THEN 1 WHEN @isdrinkingwateravailable = 0 THEN 0 WHEN @isdrinkingwateravailable = '' THEN NULL END),
	isboundarywallavailable = ( CASE WHEN @isboundarywallavailable = 1 THEN 1 WHEN @isboundarywallavailable = 0 THEN 0 WHEN @isboundarywallavailable = '' THEN NULL END),
	istoiletavailable = ( CASE WHEN @istoiletavailable = 1 THEN 1 WHEN @istoiletavailable = 0 THEN 0 WHEN @istoiletavailable = '' THEN NULL END),
	islibraryhasbooks = ( CASE WHEN @islibraryhasbooks = 1 THEN 1 WHEN @islibraryhasbooks = 0 THEN 0 WHEN @islibraryhasbooks = '' THEN NULL END),
	islibrarybooksavailable = ( CASE WHEN @islibrarybooksavailable = 1 THEN 1 WHEN @islibrarybooksavailable = 0 THEN 0 WHEN @islibrarybooksavailable = '' THEN NULL END),
	isplaygroundavailable = ( CASE WHEN @isplaygroundavailable = 1 THEN 1 WHEN @isplaygroundavailable = 0 THEN 0 WHEN @isplaygroundavailable = '' THEN NULL END),
	issportsteacheravailable = ( CASE WHEN @issportsteacheravailable = 1 THEN 1 WHEN @issportsteacheravailable = 0 THEN 0 WHEN @issportsteacheravailable = '' THEN NULL END),
	islaboratoryavailable = ( CASE WHEN @islaboratoryavailable = 1 THEN 1 WHEN @islaboratoryavailable = 0 THEN 0 WHEN @islaboratoryavailable = '' THEN NULL END),
	iscomputelabavailable = ( CASE WHEN @iscomputelabavailable = 1 THEN 1 WHEN @iscomputelabavailable = 0 THEN 0 WHEN @iscomputelabavailable = '' THEN NULL END),
	isinternetavailable = ( CASE WHEN @isinternetavailable = 1 THEN 1 WHEN @isinternetavailable = 0 THEN 0 WHEN @isinternetavailable = '' THEN NULL END),
	isclass2childrenmixed = ( CASE WHEN @isclass2childrenmixed = 1 THEN 1 WHEN @isclass2childrenmixed = 0 THEN 0 WHEN @isclass2childrenmixed = '' THEN NULL END),
	isclass8childrenmixed = ( CASE WHEN @isclass8childrenmixed = 1 THEN 1 WHEN @isclass8childrenmixed = 0 THEN 0 WHEN @isclass8childrenmixed = '' THEN NULL END);
commit;
select * from privateschool WHERE id = 640;